version: 2.1

orbs: 
  heroku: circleci/heroku@1.2.6

# Invoke jobs via workflows
workflows:
  release-workflow:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - main

jobs:
  test:
    docker:
      - image: cimg/go:1.17
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: gotestsum --junitfile test-result.xml $(go list ./... | circleci tests split --split-by=timings)
      - store_test_results:
          path: ./
  deploy:
    description: Build and Deploy Docker Image to Heroku
    docker:
      - image: cimg/base:2021.07
    steps:
      - setup_remote_docker
      - checkout
      - run: 
          name: Build Docker image
          command: docker build .
      - heroku/install
      - run:
          name: Login to Heroku Container
          command: heroku container:login
      - heroku/push-docker-image:
          app-name: zenrailz-backend
          process-types: web
      - heroku/release-docker-image:
          app-name: zenrailz-backend
          process-types: web
